### ISSUE TITLE
Function not suppose to separate the main function flow

### ISSUE THREAD

**Issue by jackhwl** [LizzyYao/PythonPractice#10]
put seam level function in one place

**Comment by LizzyYao** [comment]
Do you mean that function like "main()", then if I call main() function,all the steps just flow automatically. Does this mean "seam" ?

**Comment by jackhwl** [comment]
I mean same level, you don't need main(), you're in main by default.

this is same level mean:

func1
func2
func3

def func1

def func2

def fun 3

**Comment by LizzyYao** [comment]
I am not 100% sure if what I did is the request you made. Please help check.
