### ISSUE TITLE
Visual Studio Community

### ISSUE THREAD

**Issue by jackhwl** [LizzyYao/PythonPractice#12]
Download and install Visual Studio Community to your machine

From here: https://www.visualstudio.com/

**Comment by LizzyYao** [comment]
I have a Microsoft Visual Studio installed, 2008 version, do I need to delete that one?

**Comment by jackhwl** [comment]
no, keep it, and install the Visual Studio Community. you can have multi pal versions. 

Date: Mon, 27 Jul 2015 16:09:17 -0700
