### ISSUE TITLE
reorganize files

### ISSUE THREAD

**Issue by jackhwl** [LizzyYao/PythonPractice#2]
create a folder for daily practice only, and move all of those files to it

**Comment by LizzyYao** [comment]
What do you mean by folder? Another repo or a subrepo under this one?

**Comment by jackhwl** [comment]
check this out:
https://github.com/jackhwl/fluent-nhibernate 
or 
https://github.com/jackhwl/datasci_course_materials

you can see files and folders, what you need to do is put all of daily practice file in a folder
