### ISSUE TITLE
review function

### ISSUE THREAD

**Issue by jackhwl** [LizzyYao/PythonPractice#3]
review python function lecture and videos

**Comment by LizzyYao** [comment]
Are you able to attach the video here? I am just curious. I have to check the course, I don't remember if I download or not. And everything was on my old laptop and it's still dead.

**Comment by jackhwl** [comment]
you just need re join that course.

Date: Wed, 24 Jun 2015 07:47:10 -0700

**Comment by LizzyYao** [comment]
Oh, this is how you talk about issues in a team collaboration. I see how it works. Good.
