### ISSUE TITLE
let's finish these 4 courses before the end of July 8.

### ISSUE THREAD

**Issue by jackhwl** [LizzyYao/PythonPractice#7]
![capture](https://cloud.githubusercontent.com/assets/4327312/8379058/5618f15c-1beb-11e5-8371-223f8810b2e4.PNG)

only 13 hrs left, 13 days left.

**Comment by LizzyYao** [comment]
What? I just realized that you are like my boss. The faster I am, the more
you expect. Right?[?][?][?][?][?][?][?]

**Comment by LizzyYao** [comment]
I'll try anyways.

**Comment by jackhwl** [comment]
you close it when you finish it

**Comment by LizzyYao** [comment]
Done long time ago. :)
