### ISSUE TITLE
pick meaningful name as function name

### ISSUE THREAD

**Issue by jackhwl** [LizzyYao/PythonPractice#9]
could you find better name for those function
userInput
process
output

**Comment by LizzyYao** [comment]
how about "getNumbers, FindLargestNumber, and printLargestNumber", by the way, the function name is what you requested before. now you changed your mind? ;)

**Comment by jackhwl** [comment]
I use input process, output is the general name to give you the concept, cause that name can be used in any program, doesn't mean you need use those names.
the name you gave should match the document string insider the function, and make sense when you read them together
